aws: update ec2ssh indentation

diff --git a/topics/aws/bin/ec2ssh b/topics/aws/bin/ec2ssh
--- a/topics/aws/bin/ec2ssh
+++ b/topics/aws/bin/ec2ssh
@@ -75,36 +75,36 @@ function get_instances {
 }
 
 function transform_host {
-    hostparts=(${1/@/ })
-    user="${hostparts[0]}"
-    instance="${hostparts[1]}"
-    ip_type=${2}
+  hostparts=(${1/@/ })
+  user="${hostparts[0]}"
+  instance="${hostparts[1]}"
+  ip_type=${2}
 
-    if [ -z "${instance}" ]; then
-        instance=${user}
-        user=""
-    fi
+  if [ -z "${instance}" ]; then
+    instance=${user}
+    user=""
+  fi
 
-    if [[ ${instance} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
-        # if it looks like an ip address...
-        ipaddr=${instance}
-    else
-        ipaddr=`get_ip ${instance} ${ip_type}`
-        ipaddr=${ipaddr//\"}
-        if [ "null" = "${ipaddr}" ]; then
-          echo ${1}
-          exit
-        fi
-        if [ -z "${ipaddr}" ]; then
-           die "Failed to find instance tagged ${tag}:${instance} in ${region}"
-        fi
+  if [[ ${instance} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+    # if it looks like an ip address...
+    ipaddr=${instance}
+  else
+    ipaddr=`get_ip ${instance} ${ip_type}`
+    ipaddr=${ipaddr//\"}
+    if [ "null" = "${ipaddr}" ]; then
+      echo ${1}
+      exit
     fi
+    if [ -z "${ipaddr}" ]; then
+      die "Failed to find instance tagged ${tag}:${instance} in ${region}"
+    fi
+  fi
 
-    if [ -z "${user}" ]; then
-        echo "${ipaddr}"
-    else
-        echo "${user}@${ipaddr}"
-    fi
+  if [ -z "${user}" ]; then
+    echo "${ipaddr}"
+  else
+    echo "${user}@${ipaddr}"
+  fi
 }
 
 function add_filter {
@@ -115,8 +115,8 @@ function add_filter {
 }
 
 function die {
-    echo >&2 $1
-    exit 1
+  echo >&2 $1
+  exit 1
 }
 
 ##########################################################
@@ -150,28 +150,27 @@ CACHE_FILE="${CACHE_DIR}/${region}/${CACHE_FILE}"
 ##########################################################
 
 # parse options (and capture command for out of order)
-while test $# != 0; do
-    case "$1" in
-        -c) REFRESH_CACHE=true;;
-        -d) DRY_RUN=true;;
-        -h) CMD=$1;;
-        -l) CMD=$1;;
-        -r) region=$2; shift;;
-        -j) jump=$2; shift;;
-        -t) tag=$2; shift;;
-        -L)
-          proxy=(${2//:/ });
-          if [ ${#proxy[@]} != 3 ]; then
-            >&2 echo "ERROR: proxy port format must be [port]:[host]:[hostport]"
-            usage
-            exit 1
-          fi
-          shift
-          ;;
-        -F) jump_port=$2; shift;;
-        *)  target=$1
-    esac
-    shift
+while test $# != 0; do case "$1" in
+  -c) REFRESH_CACHE=true;;
+  -d) DRY_RUN=true;;
+  -h) CMD=$1;;
+  -l) CMD=$1;;
+  -r) region=$2; shift;;
+  -j) jump=$2; shift;;
+  -t) tag=$2; shift;;
+  -L)
+    proxy=(${2//:/ });
+      if [ ${#proxy[@]} != 3 ]; then
+        >&2 echo "ERROR: proxy port format must be [port]:[host]:[hostport]"
+        usage
+        exit 1
+      fi
+      shift
+      ;;
+    -F) jump_port=$2; shift;;
+    *)  target=$1
+  esac
+  shift
 done
 
 if [ "${REFRESH_CACHE}" = false ] && [ -f ${CACHE_FILE} ]; then
@@ -187,8 +186,8 @@ esac
 
 # ensure we have a target now
 if [ -z "${target// }" ]; then
-    usage
-    exit 1
+  usage
+  exit 1
 fi
 
 ##########################################################
@@ -197,52 +196,52 @@ fi
 # determine number of instances that matches the target, using jump to determine public or private ip
 instances=
 if [ -z "${jump}" ]; then
-    instances=$(get_instances ${target})
+  instances=$(get_instances ${target})
 else
-    instances=$(get_instances ${target} | grep -v ${jump})
+  instances=$(get_instances ${target} | grep -v ${jump})
 fi
 
 target_name=${target}
 count=$(echo "${instances}" | wc -l)
 if [[ "${count}" -eq 0 ]]; then
-    # no matching instances of target, fail
-    echo "Didn't find instance ${target}"
-    exit 1
+  # no matching instances of target, fail
+  echo "Didn't find instance ${target}"
+  exit 1
 elif [[ "${count}" -eq 1 ]]; then
-    # only one matching target, capture ip and move on
-    target=$(echo "${instances}" | cut -f1)
-    target_name=$(echo "${instances}" | cut -f2)
+  # only one matching target, capture ip and move on
+  target=$(echo "${instances}" | cut -f1)
+  target_name=$(echo "${instances}" | cut -f2)
 else
-    # print matching instance names and allow user to specify the choice by index
-    echo "${instances}" | cut -f2 | awk '{printf "%d) %s\n", NR, $0}'
-    read -p "pick (1): " pick
+  # print matching instance names and allow user to specify the choice by index
+  echo "${instances}" | cut -f2 | awk '{printf "%d) %s\n", NR, $0}'
+  read -p "pick (1): " pick
 
-    # if nothing was chosen default pick to first match
-    if [[ "${pick}" -eq "" ]]; then
-      pick=1
-    fi
+  # if nothing was chosen default pick to first match
+  if [[ "${pick}" -eq "" ]]; then
+    pick=1
+  fi
 
-    # ensure pick is within the valid range
-    if [[ "${pick}" -lt 1 || "${pick}" -gt "${count}" ]]; then
-        echo "Invalid pick"
-        exit 1
-    fi
+  # ensure pick is within the valid range
+  if [[ "${pick}" -lt 1 || "${pick}" -gt "${count}" ]]; then
+    echo "Invalid pick"
+    exit 1
+  fi
 
-    # capture ip of target for use later
-    target=$(echo "${instances}" | cut -f1 | sed -n "${pick}"p)
-    target_name=$(echo "${instances}" | cut -f2 | sed -n "${pick}"p)
+  # capture ip of target for use later
+  target=$(echo "${instances}" | cut -f1 | sed -n "${pick}"p)
+  target_name=$(echo "${instances}" | cut -f2 | sed -n "${pick}"p)
 fi
 
 ##########################################################
 # Target specific commands
 ##########################################################
 case "${CMD}" in
-    -p)
-        add_filter "Name=tag:${tag},Values=${target_name}"
-        list
-        exit;;
-    '');; # no command falls through to ssh
-    *) echo "Unhandled command: ${CMD}"; exit 1;;
+  -p)
+    add_filter "Name=tag:${tag},Values=${target_name}"
+    list
+    exit;;
+  '');; # no command falls through to ssh
+  *) echo "Unhandled command: ${CMD}"; exit 1;;
 esac
 
 cmd='ssh'
@@ -257,21 +256,21 @@ fi
 
 # if no jump server, use public ip of target
 if [ -z "${jump}" ]; then
-    public=`transform_host "${target}" "Public"`
-    if [ -z "${proxy}" ]; then
-      cmd="${cmd} ${public}"
-    else
-      cmd="${cmd} -L ${proxy[0]}:${proxy[1]}:${proxy[2]} ${public}"
-    fi
+  public=`transform_host "${target}" "Public"`
+  if [ -z "${proxy}" ]; then
+    cmd="${cmd} ${public}"
+  else
+    cmd="${cmd} -L ${proxy[0]}:${proxy[1]}:${proxy[2]} ${public}"
+  fi
 else
-    # there is a jump server, use public ip jump host and private ip of target host
-    public=`transform_host "${jump}" "Public"`
-    private=`transform_host "${target}" "Private"`
-    if [ -z "${proxy}" ]; then
-      cmd="${cmd} -A -t ${public} ssh -A ${private}"
-    else
-      cmd="${cmd} -A -L ${proxy[0]}:localhost:${jump_port} -t ${public} ssh -A -L ${jump_port}:${proxy[1]}:${proxy[2]} ${private}"
-    fi
+  # there is a jump server, use public ip jump host and private ip of target host
+  public=`transform_host "${jump}" "Public"`
+  private=`transform_host "${target}" "Private"`
+  if [ -z "${proxy}" ]; then
+    cmd="${cmd} -A -t ${public} ssh -A ${private}"
+  else
+    cmd="${cmd} -A -L ${proxy[0]}:localhost:${jump_port} -t ${public} ssh -A -L ${jump_port}:${proxy[1]}:${proxy[2]} ${private}"
+  fi
 fi
 
 echo "executing: ${cmd}"
